### ISSUE TITLE
Windows Dark Mode is blurry  

### ISSUE THREAD

**Issue by dashesy** [lutzroeder/netron#354]
Attached, Dark Mode only changes the background and therefore the edges are very hard to see compared to the light mode.
![Light](https://user-images.githubusercontent.com/873905/66875481-50ecae80-ef63-11e9-828d-db047606bafe.JPG)
![Dark](https://user-images.githubusercontent.com/873905/66875486-577b2600-ef63-11e9-92d5-093176609309.JPG)

Light mode is much better. Related to issue #290

**Comment by lutzroeder** [comment]
Would brighter edges work? How much brighter?  Colors are in `src/view-grapher.css`. For example `.edge-path` is the color used for edges. There are three definitions for 1) light 2) browser dark mode 3) desktop dark mode.

**Comment by dashesy** [comment]
I changed to 8c8c8c and it is now more visible

```css
@media (prefers-color-scheme: dark) {

    .edge-label text { fill: #b2b2b2; }
    .edge-path { stroke: #8c8c8c; }
```

![Dark](https://user-images.githubusercontent.com/873905/66946196-47b41e00-f005-11e9-8e7f-4a672a75f555.JPG)

I will also try a few other params to see if this can get better
